# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    json_placeholder.base_url: 'https://jsonplaceholder.typicode.com'
    admin.seed_email: 'admin@example.com'
    admin.seed_password: 'admin123'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Application\User\UserImportStrategy:
        alias: App\Infrastructure\Api\JsonPlaceholderUserImportStrategy

    App\Domain\User\UserRepository:
        alias: App\Infrastructure\Persistence\Doctrine\DoctrineUserRepository

    App\Domain\Task\TaskRepository:
        alias: App\Infrastructure\Persistence\Doctrine\DoctrineTaskRepository

    App\Infrastructure\Api\JsonPlaceholderUserImportStrategy:
        arguments:
            $baseUrl: '%json_placeholder.base_url%'

    App\Infrastructure\Console\SeedAdminUserCommand:
        arguments:
            $adminEmail: '%admin.seed_email%'
            $adminPassword: '%admin.seed_password%'

    App\Infrastructure\GraphQL\TaskResolver:
        tags:
            - { name: overblog_graphql.query, alias: "task_list_for_current", method: "listForCurrent" }
            - { name: overblog_graphql.query, alias: "task_list_all", method: "listAll" }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
